#
# This should only be run once.
# Creates the Environment, Secrets, and Roles for the admin namespace.
#
#
#
---
# Create user namespace
namespace: admin

apiVersion: v1
kind: Namespace
metadata:
  name: admin
  labels:
    name: admin

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: admin-manager
  namespace: admin

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: namespace-manager
  namespace: admin
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-binding
  namespace: admin
subjects:
- kind: ServiceAccount
  name: admin-manager
  namespace: admin
roleRef:
  kind: Role
  name: namespace-manager
  apiGroup: rbac.authorization.k8s.io

---
# Secret certificate for creating new tunnels
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-cert
  namespace: admin
type: Opaque
data:
  cloudflare-tunnel-cert: <INSERT CLOUDFLARE TUNNEL> 
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-key
  namespace: admin
type: Opaque
data:
  apiKey: <INSERT CLOUDFLARE TOKEN> 